"""Update tables

Revision ID: 17da931f1ffa
Revises: 
Create Date: 2025-02-24 13:44:41.640336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17da931f1ffa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('request_text', sa.String(), nullable=False),
    sa.Column('response_text', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bot_log_telegram_user_id', 'bot_logs', ['telegram_user_id'], unique=False)
    op.create_table('device_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_brands_name'), 'device_brands', ['name'], unique=True)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('retail_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_brand_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_brand_id'], ['device_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_brand_link_brand_id', 'device_brand_links', ['device_brand_id'], unique=False)
    op.create_table('device_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_brand_id'], ['device_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_model_brand_id', 'device_models', ['device_brand_id'], unique=False)
    op.create_table('repair_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_type_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['repair_type_id'], ['repair_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_repairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('repair_type_id', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['device_models.id'], ),
    sa.ForeignKeyConstraint(['repair_type_id'], ['repair_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('service_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_center_city_id', 'service_centers', ['city_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_center_id', sa.Integer(), nullable=False),
    sa.Column('device_brand_id', sa.Integer(), nullable=False),
    sa.Column('device_model_id', sa.Integer(), nullable=False),
    sa.Column('repair_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_brand_id'], ['device_brands.id'], ),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_models.id'], ),
    sa.ForeignKeyConstraint(['repair_type_id'], ['repair_types.id'], ),
    sa.ForeignKeyConstraint(['service_center_id'], ['service_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_device_brand_id', 'prices', ['device_brand_id'], unique=False)
    op.create_index('idx_price_device_model_id', 'prices', ['device_model_id'], unique=False)
    op.create_index('idx_price_repair_type_id', 'prices', ['repair_type_id'], unique=False)
    op.create_index('idx_price_service_center_id', 'prices', ['service_center_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_center_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_center_id'], ['service_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_service_center_id', 'reviews', ['service_center_id'], unique=False)
    op.create_table('service_center_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_center_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_center_id'], ['service_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_center_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('service_center_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_center_id'], ['service_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_claim_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_center_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_center_id'], ['service_centers.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_claim_service_center_id', 'service_claim_requests', ['service_center_id'], unique=False)
    op.create_index('idx_service_claim_telegram_id', 'service_claim_requests', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_service_claim_requests_id'), 'service_claim_requests', ['id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_price_id', 'price_history', ['price_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_history_price_id', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_service_claim_requests_id'), table_name='service_claim_requests')
    op.drop_index('idx_service_claim_telegram_id', table_name='service_claim_requests')
    op.drop_index('idx_service_claim_service_center_id', table_name='service_claim_requests')
    op.drop_table('service_claim_requests')
    op.drop_table('service_center_links')
    op.drop_table('service_center_addresses')
    op.drop_index('idx_review_service_center_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('idx_price_service_center_id', table_name='prices')
    op.drop_index('idx_price_repair_type_id', table_name='prices')
    op.drop_index('idx_price_device_model_id', table_name='prices')
    op.drop_index('idx_price_device_brand_id', table_name='prices')
    op.drop_table('prices')
    op.drop_index('idx_service_center_city_id', table_name='service_centers')
    op.drop_table('service_centers')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index('idx_user_telegram_id', table_name='users')
    op.drop_table('users')
    op.drop_table('model_repairs')
    op.drop_table('repair_parts')
    op.drop_index('idx_device_model_brand_id', table_name='device_models')
    op.drop_table('device_models')
    op.drop_index('idx_device_brand_link_brand_id', table_name='device_brand_links')
    op.drop_table('device_brand_links')
    op.drop_table('repair_types')
    op.drop_table('parts')
    op.drop_index(op.f('ix_device_brands_name'), table_name='device_brands')
    op.drop_table('device_brands')
    op.drop_index('idx_bot_log_telegram_user_id', table_name='bot_logs')
    op.drop_table('bot_logs')
    # ### end Alembic commands ###
