"""Update tables

Revision ID: a806ff1c033d
Revises: fbee54e3c541
Create Date: 2025-02-24 17:24:41.162119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a806ff1c033d'
down_revision: Union[str, None] = 'fbee54e3c541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_type_repair',
    sa.Column('repair_id', sa.Integer(), nullable=False),
    sa.Column('repair_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.ForeignKeyConstraint(['repair_type_id'], ['repair_types.id'], ),
    sa.PrimaryKeyConstraint('repair_id', 'repair_type_id')
    )
    op.drop_constraint('repairs_repair_type_id_fkey', 'repairs', type_='foreignkey')
    op.drop_column('repairs', 'repair_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repairs', sa.Column('repair_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('repairs_repair_type_id_fkey', 'repairs', 'repair_types', ['repair_type_id'], ['id'])
    op.drop_table('repair_type_repair')
    # ### end Alembic commands ###
