"""Update tables

Revision ID: b2f7a19dfc2e
Revises: eebd5db34e6c
Create Date: 2025-02-24 16:46:29.610885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2f7a19dfc2e'
down_revision: Union[str, None] = 'eebd5db34e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_device_brand_link_brand_id', table_name='device_brand_links')
    op.drop_table('device_brand_links')
    op.add_column('repair_types', sa.Column('group_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_types', 'group_name')
    op.create_table('device_brand_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_brand_id'], ['device_brands.id'], name='device_brand_links_device_brand_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='device_brand_links_pkey')
    )
    op.create_index('idx_device_brand_link_brand_id', 'device_brand_links', ['device_brand_id'], unique=False)
    # ### end Alembic commands ###
