"""Update tables

Revision ID: fbee54e3c541
Revises: 5797dc09144c
Create Date: 2025-02-24 17:11:04.786273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbee54e3c541'
down_revision: Union[str, None] = '5797dc09144c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repair_type_id'], ['repair_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repairs')
    # ### end Alembic commands ###
